name: Build Status

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - Development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1.0.2  # Set up MSBuild for building C++ projects
        with:
          vs-version: "latest"

      - name: Install Dependencies
        run: |
          choco install mingw
          choco install premake5

      - name: Install Premake5
        run: |
          premake5 --version  # Verify that premake5 is installed

      - name: Generate Project Files
        run: premake5 vs2022  # Generates Visual Studio project files for VS 2022

      - name: Build the Project
        run: |
          msbuild /p:Configuration=Release
